### ISSUE TITLE
What's the use of the Seed?

### ISSUE THREAD

**Issue by notflip** [xdk2mam/xdk2mam#3]

**Comment by demichele** [comment]
Hello notflip. 
If you mean the seed located at the [server.js ](https://github.com/xdk2mam/xdk2mam/blob/07783548cbe682dc703da46cebe6e799c6b7a89b/http-sdcard/xdk2mam-nodejs/server.js#L24) file of our nodejs packages, it's needed to open the MAM channel you will be using to publish messages. So, each time you want to open a new channel to start sending messages you would have to use a new seed. Otherwise you will be publishing on an already created channel together with the other messages sent before.
